<a href="https://colab.research.google.com/github/LiberationNacho/artificial-intelligence_3-2/blob/main/firstTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version

Python 3.10.12


In [ ]:
!cat /etc/issue.net

Ubuntu 22.04.3 LTS


In [ ]:
!df -h

Filesystem      Size  Used Avail Use% Mounted on
overlay         108G   33G   75G  31% /
tmpfs            64M     0   64M   0% /dev
shm             5.8G     0  5.8G   0% /dev/shm
/dev/root       2.0G  1.2G  820M  59% /usr/sbin/docker-init
tmpfs           6.4G   88K  6.4G   1% /var/colab
/dev/sda1        70G   53G   18G  75% /etc/hosts
tmpfs           6.4G     0  6.4G   0% /proc/acpi
tmpfs           6.4G     0  6.4G   0% /proc/scsi
tmpfs           6.4G     0  6.4G   0% /sys/firmware


In [ ]:
!head /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0


In [ ]:
!head /proc/meminfo

MemTotal:       13290452 kB
MemFree:         7474776 kB
MemAvailable:   12179120 kB
Buffers:          384968 kB
Cached:          4462812 kB
SwapCached:            0 kB
Active:           678396 kB
Inactive:        4772740 kB
Active(anon):       1272 kB
Inactive(anon):   603680 kB


In [ ]:
!nvidia-smi

Thu Sep 12 08:29:50 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
!pip install opencv-contrib-python

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.rand(10, 5))
df.to_csv("/content/gdrive/MyDrive/colab_test/dfs.csv")

In [ ]:
import tensorflow as tf
hello = tf.constant("Hello, TensorFlow")
print(hello)

tf.Tensor(b'Hello, TensorFlow', shape=(), dtype=string)


In [ ]:
import tensorflow as tf
tensor_a = tf.constant(3, name = 'a')
tensor_b = tf.constant(2, name = 'b')
tensor_c = tf.constant(1, name = 'c')

tensor_d = tensor_a * tensor_b
tensor_e = tensor_d + tensor_c

print(tensor_e)
print("{}".format(tensor_e))

tf.Tensor(7, shape=(), dtype=int32)
7


In [ ]:
import tensorflow as tf
tensor_a = tf.constant([[2, 1, 3], [3, 2, 1]])
print(tensor_a)

tf.Tensor(
[[2 1 3]
 [3 2 1]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf

c = [1, 2, 3, 4, 5]
print(c, type(c))

c_tensor = tf.constant(c)
print(c_tensor, type(c_tensor))
print(type(c_tensor.numpy()))

[1, 2, 3, 4, 5] <class 'list'>
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'numpy.ndarray'>


In [ ]:
import tensorflow as tf
tensor_s1 = tf.constant(1)
tensor_v1 = tf.constant([1, 2])
tensor_v2 = tf.constant([1, 2, 3])
tensor_m1 = tf.constant([[1, 2, 3], [4, 5, 6]])
tensor_m2 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor_m3 = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
tensor_m4 = tf.constant([[1], [2], [3], [4], [5], [6], [7], [8], [9]])
